/* eslint-disable */
const electronInstaller = require('electron-winstaller');
const path = require('path');
const fs = require('fs');

async function createInstaller() {
    console.log('⚡ Creating Windows Installer using Squirrel.Windows...');

    // Identify the folder generated by electron-packager
    const distPackagerDir = path.join(__dirname, 'dist-packager');
    if (!fs.existsSync(distPackagerDir)) {
        console.error(`Error: ${distPackagerDir} not found. Run "npm run build:win" first.`);
        process.exit(1);
    }

    const items = fs.readdirSync(distPackagerDir);
    const appFolder = items.find((item) => item.includes('Graphi Desktop-win32-x64'));

    if (!appFolder) {
        console.error('Error: Win32-x64 build folder not found in dist-packager/');
        process.exit(1);
    }

    const appPath = path.join(distPackagerDir, appFolder);
    const outPath = path.join(__dirname, 'dist-installer');

    try {
        await electronInstaller.createWindowsInstaller({
            appDirectory: appPath,
            outputDirectory: outPath,
            authors: 'Graphi Team',
            exe: 'Graphi Desktop.exe',
            setupExe: 'GraphiDesktopSetup.exe',
            setupIcon: path.join(__dirname, 'graphi-icon.ico'),
            noMsi: true // Skip MSI to avoid potential issues for now
        });
        console.log(`✅ Installer Created Successfully in: ${outPath}`);
    } catch (e) {
        console.error(`❌ Failed to create installer: ${e.message}`);
        process.exit(1);
    }
}

createInstaller();
